from pathlib import Path,PurePosixPath
import json,hashlib,sys,runpy,stat
E=Path(__file__).resolve().parent;R=E.parents[4];M=Path('/Users/wangweiyang/GitHub/zenpi');H=lambda b:hashlib.sha256(b).hexdigest();frozen='--frozen' in sys.argv
def read(p):return json.loads((E/p).read_text())
m=read('input-manifest.json');assert m['authority']=='3.1.20' and m['requirement_digest']=='8d525b351d066ce9b0487a485337647d47233275782e4f4d154423a623fe1645' and m['scope']=='target' and m['folder_path']=='.github';assert m['candidate_kind']=='provisional-directory-integration' and not m['acceptance_eligible'] and m['children']==m['unaccepted_children']==['ZS1-092'] and m['unaccepted_transitive_children']==['ZS1-089'];assert all(v=='[ ]' for v in m['states'].values());assert m['formal_direct_files']==[] and m['formal_direct_subdirectories']==[{'item':'ZS1-092','path':'.github/workflows'}]
inventory=read('directory-inventory.json');assert len(inventory)==1 and inventory[0]['name']=='workflows' and inventory[0]['kind']=='directory' and inventory[0]['scope']=='in-scope'
dep=read('dependency-status.json');assert dep['item']=='ZS1-092' and dep['candidate_status']=='[_]' and not dep['acceptance_eligible'];P=R/dep['copied_artifact'];raw=(P/'manifest.json').read_bytes();assert H(raw)==dep['candidate_manifest_sha256']=='1eaaba0aa72b5d4730830ff6bb7ae63d3cf5101cd422b7a25a4f1a276fa6eee3';manifest=json.loads(raw);assert manifest['status']=='[_]' and len(manifest['files'])==dep['members']==95
for row in manifest['files']:
 b=(P/'files'/row['path']).read_bytes();assert H(b)==row['sha256'] and len(b)==row['bytes']
 if not frozen:assert b==(Path(dep['candidate_path'])/'files'/row['path']).read_bytes()
rb=(P/'files'/dep['report_path']).read_bytes();assert len(rb)==dep['report_bytes']==11196 and H(rb)==dep['report_sha256']=='11936236d83981d4a54dd544287ec3160031d4d5492011c54ef22cabe7334224'
ce=P/'files/Docs/quality/stage1/ZS1-092/worker-review320';cm=json.loads((ce/'input-manifest.json').read_text());assert cm['children']==cm['unaccepted_children']==['ZS1-089'] and not cm['acceptance_eligible'];cd=json.loads((ce/'dependency-status.json').read_text());assert not cd['master_accepted'];assert [r['item'] for r in dep['dependencies']]==['ZS1-092','ZS1-089']
for row in dep['dependencies']:assert row['blueprint_state']=='[ ]' and not row['master_accepted'] and not row['main_report_exists'] and not row['main_receipt_exists']
for stem,code in [('integrity-final',0),('integrity-offline',0),('gstage-main',1)]:
 r=json.loads((ce/(stem+'.json')).read_text());b=(ce/(stem+'.log')).read_bytes();assert r['exit_code']==code and H(b)==r['sha256'] and len(b)==r['bytes']
continuity=read('descendant-continuity.json');assert len(continuity)==2
for row in continuity:
 b=(R/row['artifact']).read_bytes();assert H(b)==row['sha256'] and len(b)==row['bytes']
 if not frozen:assert Path(row['path']).read_bytes()==b and Path(row['local_path']).read_bytes()==b
authority=read('authority-context.json');assert any('均已 `[x]`' in r['text'] for r in authority['excerpts']) and any('**ZS1-093**' in r['text'] for r in authority['excerpts']);inv=read('report-inventory.json');assert not inv['main_report_existed'] and not inv['local_report_existed'] and inv['owned_path']==m['owned_report'];b=(R/inv['owned_path']).read_bytes();final=read('report-final.json');assert H(b)==final['sha256'] and len(b)==final['bytes'] and b'acceptance_eligible=false' in b
preserved=read('preserved-ready-manifests.json');assert len(preserved)==68;gate=read('gstage-main.log');receipt=read('gstage-main.json');assert receipt['exit_code']==1 and gate['structural']['ok'] and not gate['ok'] and any('ZS1-093.master.json' in v for v in gate['errors']) and H((E/'gstage-main.log').read_bytes())==receipt['sha256']
if not frozen:
 s=json.loads((M/'Docs/execution/active_requirement.json').read_text());assert s['blueprint_version']==m['authority'] and s['requirement_digest']==m['requirement_digest'];assert not (M/inv['owned_path']).exists();assert (R/dep['report_path']).read_bytes()==rb and (Path(dep['candidate_path'])/'manifest.json').read_bytes()==raw
 for row in dep['dependencies']:assert not (M/row['report_path']).exists() and not (M/row['receipt_path']).exists()
 for root in [R,M]:
  entries=list((root/m['folder_path']).iterdir());assert len(entries)==1 and entries[0].name=='workflows' and stat.S_ISDIR(entries[0].lstat().st_mode)
 for name,digest in preserved.items():assert H((R/'.ops'/name/'manifest.json').read_bytes())==digest,name
 sys.path.insert(0,str(M/'tools'));g=runpy.run_path(str(M/'tools/validate_stage1_blueprint.py'));bp=g['parse']((M/'Docs/stage_1_v3_pi_mono_blueprint.md').read_text());assert bp.requirement==m['requirement_digest'] and bp.folders['ZS1-093']==(m['scope'],m['folder_path'],m['owned_report']) and list(bp.items['ZS1-093'].depends)==m['children'];assert all(bp.items[n].state==v for n,v in m['states'].items()) and list(bp.items['ZS1-092'].depends)==['ZS1-089']
 direct=[f.item_id for f in bp.files.values() if f.scope==m['scope'] and str(PurePosixPath(f.path).parent)==m['folder_path']];assert direct==[];dirs=[{'item':k,'path':d} for k,(ss,d,a) in bp.folders.items() if ss==m['scope'] and d!='.' and str(PurePosixPath(d).parent)==m['folder_path']];assert dirs==m['formal_direct_subdirectories'];g['artifact'](R,{'path':inv['owned_path'],'bytes':len(b),'sha256':H(b)})
print(json.dumps({'ok':True,'meaning':'Provisional evidence integrity, not G-DIR acceptance','item':'ZS1-093','mode':'frozen-offline' if frozen else 'live-readonly','scope':'target:.github','physical_direct_files':0,'physical_direct_subdirectories':['workflows'],'formal_children':['ZS1-092'],'unaccepted_children':['ZS1-092'],'unaccepted_transitive_children':['ZS1-089'],'acceptance_eligible':False,'dependency_manifest_sha256':dep['candidate_manifest_sha256'],'dependency_members':95,'dependency_master_accepted':False,'report_bytes':len(b),'report_sha256':H(b),'preserved_ready_manifests':68,'gstage_exit':1,'directory_master_receipt_missing':True,'new_behavior_runs':0,'limits':'No zenpi-root integration/context promotion/product/main/state changes or Cargo/PTY/HTTP/Actions execution'},indent=2))
