import argparse,json,os,pathlib,sys
p=argparse.ArgumentParser()
p.add_argument('--samples',type=int,required=True)
p.add_argument('--output',type=pathlib.Path,required=True)
p.add_argument('--startup-evidence-dir',type=pathlib.Path,required=True)
a=p.parse_args()
assert a.samples==3 and not a.startup_evidence_dir.exists()
a.startup_evidence_dir.mkdir()
with pathlib.Path('invocations.txt').open('a') as f:f.write('invoked\n')
rc=int(os.environ['FIXTURE_BUDGET_RC'])
os.write(1,b'fixture stdout\r\n')
os.write(2,b'fixture stderr\r\n')
(a.startup_evidence_dir/'sample-00.json').write_text(json.dumps({'fixture':True,'returncode':rc})+'\n')
if rc!=17:a.output.write_text(json.dumps({'fixture':True,'ok':rc==0})+'\n')
sys.exit(rc)
