//! Shared agent state machine and command-line dispatch.
//!
//! The important boundary is admission: a request is either `Started`,
//! `Steered`, or `NotSubmitted(reason)`.  Rejected input never reaches the
//! backend and never writes a turn, which keeps races and side effects visible
//! to callers instead of hiding them behind booleans.

use std::{
    env,
    path::PathBuf,
    sync::atomic::{AtomicU64, Ordering},
    time::{SystemTime, UNIX_EPOCH},
};

use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

use crate::{
    b3::{B3Error, Handoff, HandoffRecord},
    backend::{Backend, BackendError, CompletionRequest, EchoBackend, OpenAiCompatibleBackend},
    error::ZenpiError,
    protocol::{MAX_ID_BYTES, MAX_TEXT_BYTES, TurnMode},
    session::{SessionError, SessionStore, SessionSummary},
};

static NEXT_ID: AtomicU64 = AtomicU64::new(1);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TurnRole {
    System,
    User,
    Assistant,
    Tool,
}

/// One immutable conversational record.  IDs are generated by the core and
/// parent IDs preserve the active-turn relationship for steering.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Turn {
    pub id: String,
    #[serde(default)]
    pub parent_id: Option<String>,
    pub role: TurnRole,
    pub content: String,
    pub created_at_ms: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Value>,
}

impl Turn {
    pub fn new(id: impl Into<String>, role: TurnRole, content: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            parent_id: None,
            role,
            content: content.into(),
            created_at_ms: unix_time_ms(),
            metadata: None,
        }
    }

    pub fn with_parent(
        id: impl Into<String>,
        parent_id: impl Into<String>,
        role: TurnRole,
        content: impl Into<String>,
    ) -> Self {
        let mut turn = Self::new(id, role, content);
        turn.parent_id = Some(parent_id.into());
        turn
    }

    pub fn validate(&self) -> Result<(), AgentError> {
        if self.id.trim().is_empty() {
            return Err(AgentError::InvalidTurn("turn id is empty".into()));
        }
        if self.id.len() > MAX_ID_BYTES {
            return Err(AgentError::InvalidTurn(format!(
                "turn id exceeds {MAX_ID_BYTES} bytes"
            )));
        }
        if self.id.chars().any(char::is_control) {
            return Err(AgentError::InvalidTurn(
                "turn id contains control characters".into(),
            ));
        }
        if self.parent_id.as_deref().is_some_and(|parent| {
            parent.trim().is_empty()
                || parent.len() > MAX_ID_BYTES
                || parent.chars().any(char::is_control)
        }) {
            return Err(AgentError::InvalidTurn("parent turn id is invalid".into()));
        }
        if self.content.len() > MAX_TEXT_BYTES {
            return Err(AgentError::InvalidTurn(format!(
                "turn content exceeds {MAX_TEXT_BYTES} bytes"
            )));
        }
        Ok(())
    }
}

/// Input accepted by one of the named admission paths.
#[derive(Debug, PartialEq, Eq)]
pub struct TurnInputRequest {
    pub message: String,
    pub expected_turn_id: Option<String>,
    pub mode: TurnMode,
}

impl TurnInputRequest {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
            expected_turn_id: None,
            mode: TurnMode::StartOrSteer,
        }
    }

    pub fn with_mode(mut self, mode: TurnMode) -> Self {
        self.mode = mode;
        self
    }

    pub fn expecting(mut self, turn_id: impl Into<String>) -> Self {
        self.expected_turn_id = Some(turn_id.into());
        self
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NotSubmittedReason {
    EmptyInput,
    NotIdle,
    NoActiveTurn,
    ExpectedTurnMismatch,
    ActiveTurnNotSteerable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "status")]
pub enum TurnSubmission {
    Started { turn_id: String },
    Steered { turn_id: String },
    NotSubmitted { reason: NotSubmittedReason },
}

impl TurnSubmission {
    pub fn accepted(&self) -> bool {
        !matches!(self, Self::NotSubmitted { .. })
    }

    pub fn turn_id(&self) -> Option<&str> {
        match self {
            Self::Started { turn_id } | Self::Steered { turn_id } => Some(turn_id),
            Self::NotSubmitted { .. } => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentPhase {
    Idle,
    Running,
    Closed,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    TurnAccepted {
        turn_id: String,
        mode: TurnMode,
    },
    TurnRejected {
        reason: NotSubmittedReason,
    },
    AssistantMessage {
        turn_id: String,
        content: String,
    },
    Handoff {
        handoff_id: String,
        to: Option<String>,
    },
    Error {
        message: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AgentSnapshot {
    pub session: SessionSummary,
    pub phase: AgentPhase,
    pub active_turn_id: Option<String>,
    pub backend: String,
    pub model: Option<String>,
    pub last_error: Option<String>,
}

#[derive(Debug, Error)]
pub enum AgentError {
    #[error("agent is closed")]
    Closed,
    #[error("no active turn")]
    NoActiveTurn,
    #[error("an active turn is already running")]
    NotIdle,
    #[error("invalid turn: {0}")]
    InvalidTurn(String),
    #[error("backend: {0}")]
    Backend(#[from] BackendError),
    #[error("session: {0}")]
    Session(#[from] SessionError),
    #[error("b3 handoff: {0}")]
    B3(#[from] B3Error),
}

impl AgentError {
    /// Stable machine-readable classification for headless hosts.
    pub const fn code(&self) -> &'static str {
        match self {
            Self::Closed => "agent_closed",
            Self::NoActiveTurn => "no_active_turn",
            Self::NotIdle => "agent_not_idle",
            Self::InvalidTurn(_) => "invalid_turn",
            Self::Backend(error) => error.code(),
            Self::Session(_) => "session_error",
            Self::B3(_) => "handoff_error",
        }
    }
}

/// Shared state machine used by both runtime modes.
pub struct Agent {
    backend: Box<dyn Backend>,
    session: SessionStore,
    phase: AgentPhase,
    active_turn_id: Option<String>,
    active_steerable: bool,
    model: Option<String>,
    last_error: Option<String>,
    events: Vec<AgentEvent>,
}

impl std::fmt::Debug for Agent {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("Agent")
            .field("backend", &self.backend.name())
            .field("session", &self.session.summary())
            .field("phase", &self.phase)
            .field("active_turn_id", &self.active_turn_id)
            .field("model", &self.model)
            .finish()
    }
}

impl Agent {
    pub fn new(session: SessionStore, backend: Box<dyn Backend>) -> Self {
        Self {
            backend,
            session,
            phase: AgentPhase::Idle,
            active_turn_id: None,
            active_steerable: true,
            model: None,
            last_error: None,
            events: Vec::new(),
        }
    }

    pub fn with_echo(session: SessionStore) -> Self {
        Self::new(session, Box::new(EchoBackend))
    }

    pub fn backend_name(&self) -> &str {
        self.backend.name()
    }

    pub fn session(&self) -> &SessionStore {
        &self.session
    }

    pub fn session_mut(&mut self) -> &mut SessionStore {
        &mut self.session
    }

    pub fn history(&self) -> &[Turn] {
        self.session.turns()
    }

    pub fn phase(&self) -> AgentPhase {
        self.phase
    }

    pub fn active_turn_id(&self) -> Option<&str> {
        self.active_turn_id.as_deref()
    }

    pub fn set_model(&mut self, model: Option<String>) -> Result<(), AgentError> {
        if model
            .as_deref()
            .is_some_and(|value| value.trim().is_empty())
        {
            return Err(AgentError::InvalidTurn("model name is empty".into()));
        }
        if model
            .as_deref()
            .is_some_and(|value| value.chars().any(char::is_control))
        {
            return Err(AgentError::InvalidTurn(
                "model name contains control characters".into(),
            ));
        }
        self.model = model;
        Ok(())
    }

    pub fn snapshot(&self) -> AgentSnapshot {
        AgentSnapshot {
            session: self.session.summary(),
            phase: self.phase,
            active_turn_id: self.active_turn_id.clone(),
            backend: self.backend.name().to_owned(),
            model: self.model.clone(),
            last_error: self.last_error.clone(),
        }
    }

    /// Alias used by the TUI and lightweight embedders for a single
    /// synchronous prompt.  It intentionally goes through the same typed
    /// admission path as headless mode.
    pub fn process_sync(
        &mut self,
        message: impl Into<String>,
    ) -> Result<ProcessResult, AgentError> {
        self.process(TurnInputRequest::new(message))
    }

    pub fn take_events(&mut self) -> Vec<AgentEvent> {
        std::mem::take(&mut self.events)
    }

    /// Admit a request without invoking the backend.  This named boundary is
    /// useful to UIs that want to render acceptance immediately.
    pub fn submit(&mut self, request: TurnInputRequest) -> Result<TurnSubmission, AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        if request.message.trim().is_empty() {
            let submission = TurnSubmission::NotSubmitted {
                reason: NotSubmittedReason::EmptyInput,
            };
            self.events.push(AgentEvent::TurnRejected {
                reason: NotSubmittedReason::EmptyInput,
            });
            return Ok(submission);
        }
        if request.message.len() > MAX_TEXT_BYTES {
            return Err(AgentError::InvalidTurn(format!(
                "prompt exceeds {MAX_TEXT_BYTES} bytes"
            )));
        }
        let current = self.active_turn_id.as_deref();
        if request
            .expected_turn_id
            .as_deref()
            .is_some_and(|expected| Some(expected) != current)
        {
            let submission = TurnSubmission::NotSubmitted {
                reason: NotSubmittedReason::ExpectedTurnMismatch,
            };
            self.events.push(AgentEvent::TurnRejected {
                reason: NotSubmittedReason::ExpectedTurnMismatch,
            });
            return Ok(submission);
        }

        match request.mode {
            TurnMode::StartOrSteer if current.is_none() => {
                self.start_new(request.message, TurnMode::StartOrSteer)
            }
            TurnMode::StartOrSteer => self.steer_existing(request.message),
            TurnMode::StartIfIdle if current.is_some() => {
                let submission = TurnSubmission::NotSubmitted {
                    reason: NotSubmittedReason::NotIdle,
                };
                self.events.push(AgentEvent::TurnRejected {
                    reason: NotSubmittedReason::NotIdle,
                });
                Ok(submission)
            }
            TurnMode::StartIfIdle => self.start_new(request.message, TurnMode::StartIfIdle),
            TurnMode::Steer if current.is_none() => {
                let submission = TurnSubmission::NotSubmitted {
                    reason: NotSubmittedReason::NoActiveTurn,
                };
                self.events.push(AgentEvent::TurnRejected {
                    reason: NotSubmittedReason::NoActiveTurn,
                });
                Ok(submission)
            }
            TurnMode::Steer if !self.active_steerable => {
                let submission = TurnSubmission::NotSubmitted {
                    reason: NotSubmittedReason::ActiveTurnNotSteerable,
                };
                self.events.push(AgentEvent::TurnRejected {
                    reason: NotSubmittedReason::ActiveTurnNotSteerable,
                });
                Ok(submission)
            }
            TurnMode::Steer => self.steer_existing(request.message),
        }
    }

    pub fn start_or_steer_turn(
        &mut self,
        mut request: TurnInputRequest,
    ) -> Result<TurnSubmission, AgentError> {
        request.mode = TurnMode::StartOrSteer;
        self.submit(request)
    }

    pub fn start_turn_if_idle(
        &mut self,
        mut request: TurnInputRequest,
    ) -> Result<TurnSubmission, AgentError> {
        request.mode = TurnMode::StartIfIdle;
        self.submit(request)
    }

    pub fn steer_turn(
        &mut self,
        mut request: TurnInputRequest,
    ) -> Result<TurnSubmission, AgentError> {
        request.mode = TurnMode::Steer;
        self.submit(request)
    }

    fn start_new(&mut self, message: String, mode: TurnMode) -> Result<TurnSubmission, AgentError> {
        let turn_id = next_id("turn");
        let turn = Turn::new(turn_id.clone(), TurnRole::User, message);
        turn.validate()?;
        self.session.append_turn(turn)?;
        self.active_turn_id = Some(turn_id.clone());
        self.phase = AgentPhase::Running;
        self.active_steerable = true;
        self.last_error = None;
        let submission = TurnSubmission::Started {
            turn_id: turn_id.clone(),
        };
        self.events.push(AgentEvent::TurnAccepted { turn_id, mode });
        Ok(submission)
    }

    fn steer_existing(&mut self, message: String) -> Result<TurnSubmission, AgentError> {
        let turn_id = self
            .active_turn_id
            .clone()
            .ok_or(AgentError::NoActiveTurn)?;
        let turn = Turn::with_parent(next_id("input"), turn_id.clone(), TurnRole::User, message);
        turn.validate()?;
        self.session.append_turn(turn)?;
        self.phase = AgentPhase::Running;
        self.last_error = None;
        let submission = TurnSubmission::Steered {
            turn_id: turn_id.clone(),
        };
        self.events.push(AgentEvent::TurnAccepted {
            turn_id,
            mode: TurnMode::Steer,
        });
        Ok(submission)
    }

    /// Run the currently admitted turn and append the normalized assistant
    /// response.  The active marker is cleared on both success and failure so
    /// a failed provider cannot strand the process in a permanently busy state.
    pub fn run_active_turn(&mut self) -> Result<Option<Turn>, AgentError> {
        let turn_id = self
            .active_turn_id
            .clone()
            .ok_or(AgentError::NoActiveTurn)?;
        let request = CompletionRequest {
            turn_id: &turn_id,
            turns: self.session.turns(),
            model: self.model.as_deref(),
        };
        let completion = match self.backend.complete(request) {
            Ok(completion) => completion,
            Err(error) => {
                self.last_error = Some(error.to_string());
                self.phase = AgentPhase::Idle;
                self.active_turn_id = None;
                self.events.push(AgentEvent::Error {
                    message: error.to_string(),
                });
                return Err(error.into());
            }
        };
        if completion.content.trim().is_empty() {
            let error = BackendError::EmptyResponse;
            self.last_error = Some(error.to_string());
            self.phase = AgentPhase::Idle;
            self.active_turn_id = None;
            self.events.push(AgentEvent::Error {
                message: error.to_string(),
            });
            return Err(error.into());
        }
        let mut assistant = Turn::with_parent(
            next_id("assistant"),
            turn_id.clone(),
            TurnRole::Assistant,
            completion.content,
        );
        assistant.metadata = completion
            .usage
            .map(|usage| serde_json::json!({ "usage": usage }));
        if let Err(error) = assistant.validate() {
            self.last_error = Some(error.to_string());
            self.phase = AgentPhase::Idle;
            self.active_turn_id = None;
            self.events.push(AgentEvent::Error {
                message: error.to_string(),
            });
            return Err(error);
        }
        let content = assistant.content.clone();
        if let Err(error) = self.session.append_turn(assistant.clone()) {
            self.last_error = Some(error.to_string());
            self.phase = AgentPhase::Idle;
            self.active_turn_id = None;
            self.events.push(AgentEvent::Error {
                message: error.to_string(),
            });
            return Err(error.into());
        }
        self.phase = AgentPhase::Idle;
        self.active_turn_id = None;
        self.last_error = None;
        self.events
            .push(AgentEvent::AssistantMessage { turn_id, content });
        Ok(Some(assistant))
    }

    /// Admit and, when accepted, immediately run one turn.
    pub fn process(&mut self, request: TurnInputRequest) -> Result<ProcessResult, AgentError> {
        let submission = self.submit(request)?;
        if submission.accepted() {
            let assistant = self.run_active_turn()?;
            Ok(ProcessResult {
                submission,
                assistant,
            })
        } else {
            Ok(ProcessResult {
                submission,
                assistant: None,
            })
        }
    }

    pub fn append_handoff(&mut self, handoff: Handoff) -> Result<(), AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        let handoff_id = handoff.handoff_id.clone();
        let to = handoff.to.clone();
        self.session.append_handoff(handoff)?;
        self.events.push(AgentEvent::Handoff { handoff_id, to });
        Ok(())
    }

    /// Append a signed handoff after validating it against the session
    /// boundary. The record remains opaque to the turn state machine.
    pub fn append_handoff_record(&mut self, handoff: HandoffRecord) -> Result<(), AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        handoff.validate_for(&handoff.to, self.session.session_id())?;
        let handoff_id = handoff.claim_id.clone();
        let to = Some(handoff.to.clone());
        self.session.append_handoff_record(handoff)?;
        self.events.push(AgentEvent::Handoff { handoff_id, to });
        Ok(())
    }

    /// Replace the session only while idle.  The old store is moved out only
    /// after the new path has recovered successfully.
    pub fn resume_session(&mut self, path: impl Into<PathBuf>) -> Result<(), AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        if self.phase == AgentPhase::Running {
            return Err(AgentError::NotIdle);
        }
        let replacement = SessionStore::open(path.into())?;
        self.session = replacement;
        self.phase = AgentPhase::Idle;
        self.active_turn_id = None;
        self.last_error = None;
        Ok(())
    }

    pub fn close(&mut self) {
        self.phase = AgentPhase::Closed;
        self.active_turn_id = None;
    }
}

#[derive(Debug)]
pub struct ProcessResult {
    pub submission: TurnSubmission,
    pub assistant: Option<Turn>,
}

fn unix_time_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
        .min(u128::from(u64::MAX)) as u64
}

fn next_id(prefix: &str) -> String {
    format!(
        "{prefix}-{}-{}",
        unix_time_ms(),
        NEXT_ID.fetch_add(1, Ordering::Relaxed)
    )
}

/// Runtime mode.  There are intentionally only these two variants.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunMode {
    Tui,
    Headless,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CliOptions {
    pub mode: RunMode,
    pub session: PathBuf,
    pub backend: String,
    pub model: Option<String>,
    pub help: bool,
}

impl Default for CliOptions {
    fn default() -> Self {
        Self {
            mode: RunMode::Tui,
            session: SessionStore::default_path(),
            backend: "echo".into(),
            model: None,
            help: false,
        }
    }
}

pub fn parse_args<I, S>(args: I) -> Result<CliOptions, ZenpiError>
where
    I: IntoIterator<Item = S>,
    S: Into<String>,
{
    let mut options = CliOptions::default();
    let mut args = args.into_iter().map(Into::into).peekable();
    while let Some(argument) = args.next() {
        let (flag, inline) = argument
            .split_once('=')
            .map_or((argument.as_str(), None), |(flag, value)| {
                (flag, Some(value))
            });
        match flag {
            "--help" | "-h" => options.help = true,
            "--headless" => {
                if inline.is_some() {
                    return Err(ZenpiError::arguments("--headless does not take a value"));
                }
                options.mode = RunMode::Headless;
            }
            "--tui" => {
                if inline.is_some() {
                    return Err(ZenpiError::arguments("--tui does not take a value"));
                }
                options.mode = RunMode::Tui;
            }
            "--mode" => {
                let value = inline
                    .map(str::to_owned)
                    .or_else(|| args.next())
                    .ok_or_else(|| ZenpiError::arguments("--mode requires tui or headless"))?;
                options.mode = match value.as_str() {
                    "tui" => RunMode::Tui,
                    "headless" => RunMode::Headless,
                    _ => return Err(ZenpiError::arguments("--mode must be tui or headless")),
                };
            }
            "--session" => {
                let value = inline
                    .map(str::to_owned)
                    .or_else(|| args.next())
                    .ok_or_else(|| ZenpiError::arguments("--session requires a path"))?;
                if value.trim().is_empty() {
                    return Err(ZenpiError::arguments("--session path is empty"));
                }
                options.session = PathBuf::from(value);
            }
            "--backend" => {
                options.backend = inline
                    .map(str::to_owned)
                    .or_else(|| args.next())
                    .ok_or_else(|| ZenpiError::arguments("--backend requires echo or openai"))?;
                if options.backend.trim().is_empty()
                    || options.backend.chars().any(char::is_control)
                {
                    return Err(ZenpiError::arguments("--backend name is invalid"));
                }
            }
            "--model" => {
                let model = inline
                    .map(str::to_owned)
                    .or_else(|| args.next())
                    .ok_or_else(|| ZenpiError::arguments("--model requires a name"))?;
                if model.trim().is_empty()
                    || model.len() > 256
                    || model.chars().any(char::is_control)
                {
                    return Err(ZenpiError::arguments(
                        "--model must be non-empty and at most 256 bytes",
                    ));
                }
                options.model = Some(model);
            }
            other if other.starts_with('-') => {
                return Err(ZenpiError::arguments(format!("unknown option `{other}`")));
            }
            other => {
                return Err(ZenpiError::arguments(format!(
                    "unexpected argument `{other}`"
                )));
            }
        }
    }
    Ok(options)
}

fn make_backend(options: &CliOptions) -> Result<Box<dyn Backend>, ZenpiError> {
    match options.backend.as_str() {
        "echo" => Ok(Box::new(EchoBackend)),
        "openai" => {
            let mut backend = OpenAiCompatibleBackend::from_env()?;
            if let Some(model) = &options.model {
                backend = OpenAiCompatibleBackend::new(
                    backend.endpoint().to_owned(),
                    env::var("ZENPI_API_KEY")
                        .or_else(|_| env::var("OPENAI_API_KEY"))
                        .ok(),
                    model,
                )?;
            }
            Ok(Box::new(backend))
        }
        other => Err(ZenpiError::arguments(format!(
            "unknown backend `{other}` (expected echo or openai)"
        ))),
    }
}

fn print_help() {
    println!("zenpi [--mode tui|headless] [--session PATH] [--backend echo|openai] [--model NAME]");
}

/// Binary entry point shared with tests and embedders.
pub fn run() -> Result<(), ZenpiError> {
    let options = parse_args(env::args().skip(1))?;
    if options.help {
        print_help();
        return Ok(());
    }
    let backend = make_backend(&options)?;
    let session = SessionStore::open(&options.session)?;
    let mut agent = Agent::new(session, backend);
    if let Some(model) = options.model {
        agent.set_model(Some(model))?;
    }
    match options.mode {
        RunMode::Headless => crate::headless::run_stdio(&mut agent)
            .map_err(|error| ZenpiError::Message(error.to_string())),
        RunMode::Tui => crate::tui::run(&mut agent),
    }
}
