//! Shared agent state machine and command-line dispatch.
//!
//! The important boundary is admission: a request is either `Started`,
//! `Steered`, or `NotSubmitted(reason)`.  Rejected input never reaches the
//! backend and never writes a turn, which keeps races and side effects visible
//! to callers instead of hiding them behind booleans.

use std::{
    env,
    path::PathBuf,
    sync::atomic::{AtomicU64, Ordering},
    time::{SystemTime, UNIX_EPOCH},
};

use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

use crate::{
    approval::{ApprovalCoordinator, ApprovalDecision, ApprovalPolicy, ApprovalRequest},
    b3::{B3Error, Handoff, HandoffRecord},
    backend::{
        Backend, BackendError, CompletionRequest, EchoBackend, OpenAiCompatibleBackend,
        OpenAiWireApi, ProviderEvent,
    },
    error::ZenpiError,
    protocol::{MAX_ID_BYTES, MAX_TEXT_BYTES, TurnMode},
    session::{SessionError, SessionStore, SessionSummary},
    tools::{SideEffectPolicy, ToolContext, ToolError, ToolRegistry},
};

static NEXT_ID: AtomicU64 = AtomicU64::new(1);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TurnRole {
    System,
    User,
    Assistant,
    Tool,
}

/// One immutable conversational record.  IDs are generated by the core and
/// parent IDs preserve the active-turn relationship for steering.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Turn {
    pub id: String,
    #[serde(default)]
    pub parent_id: Option<String>,
    pub role: TurnRole,
    pub content: String,
    pub created_at_ms: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Value>,
}

impl Turn {
    pub fn new(id: impl Into<String>, role: TurnRole, content: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            parent_id: None,
            role,
            content: content.into(),
            created_at_ms: unix_time_ms(),
            metadata: None,
        }
    }

    pub fn with_parent(
        id: impl Into<String>,
        parent_id: impl Into<String>,
        role: TurnRole,
        content: impl Into<String>,
    ) -> Self {
        let mut turn = Self::new(id, role, content);
        turn.parent_id = Some(parent_id.into());
        turn
    }

    pub fn validate(&self) -> Result<(), AgentError> {
        if self.id.trim().is_empty() {
            return Err(AgentError::InvalidTurn("turn id is empty".into()));
        }
        if self.id.len() > MAX_ID_BYTES {
            return Err(AgentError::InvalidTurn(format!(
                "turn id exceeds {MAX_ID_BYTES} bytes"
            )));
        }
        if self.id.chars().any(char::is_control) {
            return Err(AgentError::InvalidTurn(
                "turn id contains control characters".into(),
            ));
        }
        if self.parent_id.as_deref().is_some_and(|parent| {
            parent.trim().is_empty()
                || parent.len() > MAX_ID_BYTES
                || parent.chars().any(char::is_control)
        }) {
            return Err(AgentError::InvalidTurn("parent turn id is invalid".into()));
        }
        if self.content.len() > MAX_TEXT_BYTES {
            return Err(AgentError::InvalidTurn(format!(
                "turn content exceeds {MAX_TEXT_BYTES} bytes"
            )));
        }
        Ok(())
    }
}

/// Input accepted by one of the named admission paths.
#[derive(Debug, PartialEq, Eq)]
pub struct TurnInputRequest {
    pub message: String,
    pub expected_turn_id: Option<String>,
    pub mode: TurnMode,
    pub attachments: Vec<crate::backend::InputAttachment>,
}

impl TurnInputRequest {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
            expected_turn_id: None,
            mode: TurnMode::StartOrSteer,
            attachments: Vec::new(),
        }
    }

    pub fn with_mode(mut self, mode: TurnMode) -> Self {
        self.mode = mode;
        self
    }

    pub fn expecting(mut self, turn_id: impl Into<String>) -> Self {
        self.expected_turn_id = Some(turn_id.into());
        self
    }

    pub fn with_attachments(mut self, attachments: Vec<crate::backend::InputAttachment>) -> Self {
        self.attachments = attachments;
        self
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NotSubmittedReason {
    EmptyInput,
    NotIdle,
    NoActiveTurn,
    ExpectedTurnMismatch,
    ActiveTurnNotSteerable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "status")]
pub enum TurnSubmission {
    Started { turn_id: String },
    Steered { turn_id: String },
    NotSubmitted { reason: NotSubmittedReason },
}

impl TurnSubmission {
    pub fn accepted(&self) -> bool {
        !matches!(self, Self::NotSubmitted { .. })
    }

    pub fn turn_id(&self) -> Option<&str> {
        match self {
            Self::Started { turn_id } | Self::Steered { turn_id } => Some(turn_id),
            Self::NotSubmitted { .. } => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentPhase {
    Idle,
    Running,
    Closed,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    TurnAccepted {
        turn_id: String,
        mode: TurnMode,
    },
    TurnRejected {
        reason: NotSubmittedReason,
    },
    AssistantMessage {
        turn_id: String,
        content: String,
    },
    Handoff {
        handoff_id: String,
        to: Option<String>,
    },
    ToolCall {
        turn_id: String,
        call_id: String,
        tool: String,
    },
    ToolResult {
        turn_id: String,
        call_id: String,
        success: bool,
    },
    Provider {
        turn_id: String,
        event: ProviderEvent,
    },
    Error {
        message: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AgentSnapshot {
    pub session: SessionSummary,
    pub phase: AgentPhase,
    pub active_turn_id: Option<String>,
    pub backend: String,
    pub model: Option<String>,
    pub last_error: Option<String>,
}

#[derive(Debug, Error)]
pub enum AgentError {
    #[error("agent is closed")]
    Closed,
    #[error("no active turn")]
    NoActiveTurn,
    #[error("an active turn is already running")]
    NotIdle,
    #[error("invalid turn: {0}")]
    InvalidTurn(String),
    #[error("backend: {0}")]
    Backend(#[from] BackendError),
    #[error("session: {0}")]
    Session(#[from] SessionError),
    #[error("b3 handoff: {0}")]
    B3(#[from] B3Error),
    #[error("tool: {0}")]
    Tool(#[from] ToolError),
    #[error("tool loop exceeded {0} iterations")]
    ToolLoopLimit(usize),
    #[error("operation recovery: {0}")]
    Recovery(String),
    #[error("resource governance: {0}")]
    Governance(String),
}

impl AgentError {
    /// Stable machine-readable classification for headless hosts.
    pub const fn code(&self) -> &'static str {
        match self {
            Self::Closed => "agent_closed",
            Self::NoActiveTurn => "no_active_turn",
            Self::NotIdle => "agent_not_idle",
            Self::InvalidTurn(_) => "invalid_turn",
            Self::Backend(error) => error.code(),
            Self::Session(_) => "session_error",
            Self::B3(_) => "handoff_error",
            Self::Tool(_) => "tool_error",
            Self::ToolLoopLimit(_) => "tool_loop_limit",
            Self::Recovery(_) => "operation_recovery",
            Self::Governance(_) => "resource_budget_exceeded",
        }
    }
}

/// Shared state machine used by both runtime modes.
pub struct Agent {
    backend: Box<dyn Backend>,
    session: SessionStore,
    phase: AgentPhase,
    active_turn_id: Option<String>,
    active_steerable: bool,
    model: Option<String>,
    last_error: Option<String>,
    events: Vec<AgentEvent>,
    tools: Option<ToolRuntime>,
    context_budget: crate::context::ContextBudget,
    skills: crate::skills::SkillSet,
    active_attachments: Vec<crate::backend::RequestAttachment>,
    governance: Option<crate::governance::BudgetLedger>,
}

struct ToolRuntime {
    registry: ToolRegistry,
    context: ToolContext,
    policy: SideEffectPolicy,
    approval: ApprovalCoordinator,
    approval_policy: ApprovalPolicy,
}

impl std::fmt::Debug for Agent {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("Agent")
            .field("backend", &self.backend.name())
            .field("session", &self.session.summary())
            .field("phase", &self.phase)
            .field("active_turn_id", &self.active_turn_id)
            .field("model", &self.model)
            .finish()
    }
}

impl Agent {
    pub fn new(session: SessionStore, backend: Box<dyn Backend>) -> Self {
        let model = backend.model().map(str::to_owned);
        let recovered = session.interrupted_operations();
        let mut agent = Self {
            backend,
            session,
            phase: AgentPhase::Idle,
            active_turn_id: None,
            active_steerable: true,
            model,
            last_error: None,
            events: Vec::new(),
            tools: None,
            context_budget: crate::context::ContextBudget::default(),
            skills: crate::skills::SkillSet::default(),
            active_attachments: Vec::new(),
            governance: None,
        };
        for operation in recovered {
            agent.events.push(AgentEvent::Error {
                message: format!(
                    "interrupted {:?} operation {} requires explicit retry",
                    operation.kind, operation.operation_id
                ),
            });
        }
        agent
    }

    /// Persist terminal interruption markers for operations left open by a
    /// previous process. This is separate from construction so embedders can
    /// inspect recovery state without mutating the journal.
    pub fn acknowledge_recovery(
        &mut self,
    ) -> Result<Vec<crate::session::InterruptedOperation>, AgentError> {
        self.session
            .mark_interrupted_operations()
            .map_err(AgentError::from)
    }

    pub fn with_echo(session: SessionStore) -> Self {
        Self::new(session, Box::new(EchoBackend))
    }

    pub fn backend_name(&self) -> &str {
        self.backend.name()
    }

    pub fn session(&self) -> &SessionStore {
        &self.session
    }

    pub fn session_mut(&mut self) -> &mut SessionStore {
        &mut self.session
    }

    pub fn history(&self) -> &[Turn] {
        self.session.turns()
    }

    pub fn phase(&self) -> AgentPhase {
        self.phase
    }

    pub fn active_turn_id(&self) -> Option<&str> {
        self.active_turn_id.as_deref()
    }

    pub fn set_model(&mut self, model: Option<String>) -> Result<(), AgentError> {
        if model
            .as_deref()
            .is_some_and(|value| value.trim().is_empty())
        {
            return Err(AgentError::InvalidTurn("model name is empty".into()));
        }
        if model
            .as_deref()
            .is_some_and(|value| value.chars().any(char::is_control))
        {
            return Err(AgentError::InvalidTurn(
                "model name contains control characters".into(),
            ));
        }
        self.model = model;
        Ok(())
    }

    pub fn snapshot(&self) -> AgentSnapshot {
        AgentSnapshot {
            session: self.session.summary(),
            phase: self.phase,
            active_turn_id: self.active_turn_id.clone(),
            backend: self.backend.name().to_owned(),
            model: self.model.clone(),
            last_error: self.last_error.clone(),
        }
    }

    /// Alias used by the TUI and lightweight embedders for a single
    /// synchronous prompt.  It intentionally goes through the same typed
    /// admission path as headless mode.
    pub fn process_sync(
        &mut self,
        message: impl Into<String>,
    ) -> Result<ProcessResult, AgentError> {
        self.process(TurnInputRequest::new(message))
    }

    pub fn take_events(&mut self) -> Vec<AgentEvent> {
        std::mem::take(&mut self.events)
    }

    /// Install a bounded tool registry for subsequent provider turns. The
    /// default agent has no tools, so embedders must opt in explicitly.
    pub fn set_tools(
        &mut self,
        registry: ToolRegistry,
        context: ToolContext,
        policy: SideEffectPolicy,
    ) {
        self.tools = Some(ToolRuntime {
            registry,
            context,
            policy,
            approval: ApprovalCoordinator::new(),
            approval_policy: ApprovalPolicy::default(),
        });
    }

    pub fn set_attachment_workspace(&mut self, context: ToolContext) {
        if let Some(runtime) = self.tools.as_mut() {
            runtime.context = context;
        } else {
            self.tools = Some(ToolRuntime {
                registry: ToolRegistry::new(),
                context,
                policy: SideEffectPolicy::read_only(),
                approval: ApprovalCoordinator::new(),
                approval_policy: ApprovalPolicy::default(),
            });
        }
    }

    /// Configure the approval policy and return the coordinator used by a
    /// host to surface/respond to pending side-effect requests.
    pub fn set_approval_policy(&mut self, policy: ApprovalPolicy) -> Option<ApprovalCoordinator> {
        let runtime = self.tools.as_mut()?;
        runtime.approval_policy = policy;
        Some(runtime.approval.clone())
    }

    pub fn approval_coordinator(&self) -> Option<ApprovalCoordinator> {
        self.tools.as_ref().map(|runtime| runtime.approval.clone())
    }

    pub fn set_context_budget(&mut self, budget: crate::context::ContextBudget) {
        self.context_budget = budget;
    }

    pub fn set_skills(&mut self, skills: crate::skills::SkillSet) {
        self.skills = skills;
    }

    pub fn set_resource_limits(
        &mut self,
        limits: crate::governance::ResourceLimits,
    ) -> Result<(), AgentError> {
        self.governance = Some(
            crate::governance::BudgetLedger::restore(&self.session, limits)
                .map_err(|error| AgentError::Governance(error.to_string()))?,
        );
        Ok(())
    }

    /// Admit a request without invoking the backend.  This named boundary is
    /// useful to UIs that want to render acceptance immediately.
    pub fn submit(&mut self, request: TurnInputRequest) -> Result<TurnSubmission, AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        if request.message.trim().is_empty() {
            let submission = TurnSubmission::NotSubmitted {
                reason: NotSubmittedReason::EmptyInput,
            };
            self.events.push(AgentEvent::TurnRejected {
                reason: NotSubmittedReason::EmptyInput,
            });
            return Ok(submission);
        }
        if request.message.len() > MAX_TEXT_BYTES {
            return Err(AgentError::InvalidTurn(format!(
                "prompt exceeds {MAX_TEXT_BYTES} bytes"
            )));
        }
        if request.attachments.len() > crate::backend::MAX_ATTACHMENTS_PER_TURN {
            return Err(AgentError::InvalidTurn(format!(
                "prompt exceeds {} attachments",
                crate::backend::MAX_ATTACHMENTS_PER_TURN
            )));
        }
        for attachment in &request.attachments {
            attachment.validate()?;
        }
        let current = self.active_turn_id.as_deref();
        if request
            .expected_turn_id
            .as_deref()
            .is_some_and(|expected| Some(expected) != current)
        {
            let submission = TurnSubmission::NotSubmitted {
                reason: NotSubmittedReason::ExpectedTurnMismatch,
            };
            self.events.push(AgentEvent::TurnRejected {
                reason: NotSubmittedReason::ExpectedTurnMismatch,
            });
            return Ok(submission);
        }

        match request.mode {
            TurnMode::StartOrSteer if current.is_none() => {
                self.start_new(request.message, request.attachments, TurnMode::StartOrSteer)
            }
            TurnMode::StartOrSteer => self.steer_existing(request.message, request.attachments),
            TurnMode::StartIfIdle if current.is_some() => {
                let submission = TurnSubmission::NotSubmitted {
                    reason: NotSubmittedReason::NotIdle,
                };
                self.events.push(AgentEvent::TurnRejected {
                    reason: NotSubmittedReason::NotIdle,
                });
                Ok(submission)
            }
            TurnMode::StartIfIdle => {
                self.start_new(request.message, request.attachments, TurnMode::StartIfIdle)
            }
            TurnMode::Steer if current.is_none() => {
                let submission = TurnSubmission::NotSubmitted {
                    reason: NotSubmittedReason::NoActiveTurn,
                };
                self.events.push(AgentEvent::TurnRejected {
                    reason: NotSubmittedReason::NoActiveTurn,
                });
                Ok(submission)
            }
            TurnMode::Steer if !self.active_steerable => {
                let submission = TurnSubmission::NotSubmitted {
                    reason: NotSubmittedReason::ActiveTurnNotSteerable,
                };
                self.events.push(AgentEvent::TurnRejected {
                    reason: NotSubmittedReason::ActiveTurnNotSteerable,
                });
                Ok(submission)
            }
            TurnMode::Steer => self.steer_existing(request.message, request.attachments),
        }
    }

    pub fn start_or_steer_turn(
        &mut self,
        mut request: TurnInputRequest,
    ) -> Result<TurnSubmission, AgentError> {
        request.mode = TurnMode::StartOrSteer;
        self.submit(request)
    }

    pub fn start_turn_if_idle(
        &mut self,
        mut request: TurnInputRequest,
    ) -> Result<TurnSubmission, AgentError> {
        request.mode = TurnMode::StartIfIdle;
        self.submit(request)
    }

    pub fn steer_turn(
        &mut self,
        mut request: TurnInputRequest,
    ) -> Result<TurnSubmission, AgentError> {
        request.mode = TurnMode::Steer;
        self.submit(request)
    }

    fn start_new(
        &mut self,
        message: String,
        attachments: Vec<crate::backend::InputAttachment>,
        mode: TurnMode,
    ) -> Result<TurnSubmission, AgentError> {
        let turn_id = next_id("turn");
        let mut turn = Turn::new(turn_id.clone(), TurnRole::User, message);
        let materialized = self.materialize_attachments(&turn_id, &attachments)?;
        if !attachments.is_empty() {
            turn.metadata = Some(serde_json::json!({
                "attachments": attachment_journal_metadata(&materialized),
            }));
        }
        turn.validate()?;
        self.session.append_turn(turn)?;
        self.active_attachments = materialized;
        self.active_turn_id = Some(turn_id.clone());
        self.phase = AgentPhase::Running;
        self.active_steerable = true;
        self.last_error = None;
        let submission = TurnSubmission::Started {
            turn_id: turn_id.clone(),
        };
        self.events.push(AgentEvent::TurnAccepted { turn_id, mode });
        Ok(submission)
    }

    fn steer_existing(
        &mut self,
        message: String,
        attachments: Vec<crate::backend::InputAttachment>,
    ) -> Result<TurnSubmission, AgentError> {
        let turn_id = self
            .active_turn_id
            .clone()
            .ok_or(AgentError::NoActiveTurn)?;
        let input_id = next_id("input");
        let mut turn =
            Turn::with_parent(input_id.clone(), turn_id.clone(), TurnRole::User, message);
        let materialized = self.materialize_attachments(&input_id, &attachments)?;
        if !attachments.is_empty() {
            turn.metadata = Some(serde_json::json!({
                "attachments": attachment_journal_metadata(&materialized),
            }));
        }
        turn.validate()?;
        self.session.append_turn(turn)?;
        self.active_attachments.extend(materialized);
        self.phase = AgentPhase::Running;
        self.last_error = None;
        let submission = TurnSubmission::Steered {
            turn_id: turn_id.clone(),
        };
        self.events.push(AgentEvent::TurnAccepted {
            turn_id,
            mode: TurnMode::Steer,
        });
        Ok(submission)
    }

    fn start_reissued(
        &mut self,
        message: String,
        superseded_turn_id: &str,
    ) -> Result<TurnSubmission, AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        if self.phase != AgentPhase::Idle {
            return Err(AgentError::NotIdle);
        }
        if message.trim().is_empty() || message.len() > MAX_TEXT_BYTES {
            return Err(AgentError::InvalidTurn(
                "steer reissue message is empty or too large".into(),
            ));
        }
        if superseded_turn_id.trim().is_empty() || superseded_turn_id.len() > MAX_ID_BYTES {
            return Err(AgentError::InvalidTurn(
                "superseded turn ID is invalid".into(),
            ));
        }
        let turn_id = next_id("turn");
        let mut turn = Turn::with_parent(
            turn_id.clone(),
            superseded_turn_id.to_owned(),
            TurnRole::User,
            message,
        );
        turn.metadata = Some(serde_json::json!({
            "steer": {
                "strategy": "cancel_reissue",
                "superseded_turn_id": superseded_turn_id,
            }
        }));
        turn.validate()?;
        self.session.append_turn(turn)?;
        self.active_turn_id = Some(turn_id.clone());
        self.phase = AgentPhase::Running;
        self.active_steerable = true;
        self.last_error = None;
        self.events.push(AgentEvent::TurnAccepted {
            turn_id: turn_id.clone(),
            mode: TurnMode::Steer,
        });
        Ok(TurnSubmission::Steered { turn_id })
    }

    fn materialize_attachments(
        &self,
        input_turn_id: &str,
        attachments: &[crate::backend::InputAttachment],
    ) -> Result<Vec<crate::backend::RequestAttachment>, AgentError> {
        use sha2::{Digest, Sha256};

        let mut total = 0_usize;
        let mut materialized = Vec::with_capacity(attachments.len());
        for input in attachments {
            input.validate()?;
            let (filename, data, size_bytes, sha256) = if let Some(path) = &input.path {
                let runtime = self.tools.as_ref().ok_or_else(|| {
                    AgentError::InvalidTurn(
                        "workspace attachments require a configured tool workspace".into(),
                    )
                })?;
                let (relative, bytes) = runtime
                    .context
                    .read_attachment(path, crate::backend::MAX_ATTACHMENT_BYTES)?;
                let size = bytes.len();
                total = total.saturating_add(size);
                if total > crate::backend::MAX_TOTAL_ATTACHMENT_BYTES {
                    return Err(AgentError::InvalidTurn(format!(
                        "attachments exceed {} total bytes",
                        crate::backend::MAX_TOTAL_ATTACHMENT_BYTES
                    )));
                }
                let digest = format!("{:x}", Sha256::digest(&bytes));
                (
                    relative
                        .file_name()
                        .and_then(|name| name.to_str())
                        .map(str::to_owned),
                    Some(bytes),
                    Some(u64::try_from(size).unwrap_or(u64::MAX)),
                    Some(digest),
                )
            } else {
                (None, None, None, None)
            };
            materialized.push(crate::backend::RequestAttachment {
                turn_id: input_turn_id.to_owned(),
                input: input.clone(),
                filename,
                data,
                size_bytes,
                sha256,
            });
        }
        Ok(materialized)
    }

    /// Run the currently admitted turn and append the normalized assistant
    /// response.  The active marker is cleared on both success and failure so
    /// a failed provider cannot strand the process in a permanently busy state.
    pub fn run_active_turn(&mut self) -> Result<Option<Turn>, AgentError> {
        self.run_active_turn_cancelable(|| false)
    }

    /// Run the active turn while allowing the host to veto a completion
    /// before it is persisted. This keeps a late cancellation from leaking an
    /// assistant answer into the journal after the caller requested stop.
    pub fn run_active_turn_cancelable<F>(
        &mut self,
        is_cancelled: F,
    ) -> Result<Option<Turn>, AgentError>
    where
        F: Fn() -> bool,
    {
        let mut events = Vec::new();
        let turn_id = self.active_turn_id.clone();
        let result = self.run_active_turn_cancelable_with_events(is_cancelled, &mut |event| {
            events.push(event);
            Ok(())
        });
        for event in events {
            self.events.push(AgentEvent::Provider {
                // Capture the ID before the run clears the active marker on
                // success/failure; provider events must remain correlated to
                // the turn that produced them.
                turn_id: turn_id.clone().unwrap_or_else(|| "unknown".into()),
                event,
            });
        }
        result
    }

    pub fn run_active_turn_cancelable_with_events<F, E>(
        &mut self,
        is_cancelled: F,
        provider_sink: &mut E,
    ) -> Result<Option<Turn>, AgentError>
    where
        F: Fn() -> bool,
        E: FnMut(ProviderEvent) -> Result<(), BackendError>,
    {
        let turn_id = self
            .active_turn_id
            .clone()
            .ok_or(AgentError::NoActiveTurn)?;
        let provider_operation = crate::session::InterruptedOperation {
            operation_id: format!("provider-{turn_id}"),
            kind: crate::session::OperationKind::Provider,
            turn_id: turn_id.clone(),
            retry_requires_confirmation: false,
        };
        self.session.begin_operation(&provider_operation)?;
        const MAX_TOOL_ITERATIONS: usize = 8;
        let completion = match self.complete_with_tools(
            &turn_id,
            MAX_TOOL_ITERATIONS,
            &is_cancelled,
            provider_sink,
        ) {
            Ok(completion) => completion,
            Err(error) => {
                let outcome = if matches!(
                    error,
                    AgentError::Backend(BackendError::Cancelled | BackendError::Steered)
                ) {
                    crate::session::OperationOutcome::Cancelled
                } else {
                    crate::session::OperationOutcome::Failed
                };
                self.session
                    .finish_operation(&provider_operation.operation_id, outcome)?;
                self.last_error = Some(error.to_string());
                self.phase = AgentPhase::Idle;
                self.active_turn_id = None;
                self.active_attachments.clear();
                self.events.push(AgentEvent::Error {
                    message: error.to_string(),
                });
                return Err(error);
            }
        };
        if is_cancelled() {
            let error = BackendError::Cancelled;
            self.last_error = Some(error.to_string());
            self.phase = AgentPhase::Idle;
            self.active_turn_id = None;
            self.active_attachments.clear();
            self.session.finish_operation(
                &provider_operation.operation_id,
                crate::session::OperationOutcome::Cancelled,
            )?;
            return Err(error.into());
        }
        if completion.content.trim().is_empty() {
            let error = BackendError::EmptyResponse;
            self.last_error = Some(error.to_string());
            self.phase = AgentPhase::Idle;
            self.active_turn_id = None;
            self.active_attachments.clear();
            self.events.push(AgentEvent::Error {
                message: error.to_string(),
            });
            self.session.finish_operation(
                &provider_operation.operation_id,
                crate::session::OperationOutcome::Failed,
            )?;
            return Err(error.into());
        }
        let mut assistant = Turn::with_parent(
            next_id("assistant"),
            turn_id.clone(),
            TurnRole::Assistant,
            completion.content,
        );
        let mut metadata = serde_json::Map::new();
        if let Some(usage) = completion.usage {
            metadata.insert("usage".into(), serde_json::json!(usage));
        }
        if let Some(response_id) = completion.response_id {
            metadata.insert("response_id".into(), serde_json::json!(response_id));
        }
        if let Some(model) = completion.model {
            metadata.insert("model".into(), serde_json::json!(model));
        }
        if let Some(refusal) = completion.refusal {
            metadata.insert("refusal".into(), serde_json::json!(refusal));
        }
        if !completion.annotations.is_empty() {
            metadata.insert("annotations".into(), Value::Array(completion.annotations));
        }
        assistant.metadata = (!metadata.is_empty()).then_some(Value::Object(metadata));
        if let Err(error) = assistant.validate() {
            self.last_error = Some(error.to_string());
            self.phase = AgentPhase::Idle;
            self.active_turn_id = None;
            self.active_attachments.clear();
            self.events.push(AgentEvent::Error {
                message: error.to_string(),
            });
            self.session.finish_operation(
                &provider_operation.operation_id,
                crate::session::OperationOutcome::Failed,
            )?;
            return Err(error);
        }
        let content = assistant.content.clone();
        if let Err(error) = self.session.append_turn(assistant.clone()) {
            self.last_error = Some(error.to_string());
            self.phase = AgentPhase::Idle;
            self.active_turn_id = None;
            self.active_attachments.clear();
            self.events.push(AgentEvent::Error {
                message: error.to_string(),
            });
            self.session.finish_operation(
                &provider_operation.operation_id,
                crate::session::OperationOutcome::Failed,
            )?;
            return Err(error.into());
        }
        self.phase = AgentPhase::Idle;
        self.active_turn_id = None;
        self.active_attachments.clear();
        self.last_error = None;
        self.session.finish_operation(
            &provider_operation.operation_id,
            crate::session::OperationOutcome::Succeeded,
        )?;
        self.events
            .push(AgentEvent::AssistantMessage { turn_id, content });
        Ok(Some(assistant))
    }

    fn complete_with_tools<F, E>(
        &mut self,
        turn_id: &str,
        max_iterations: usize,
        is_cancelled: &F,
        provider_sink: &mut E,
    ) -> Result<crate::backend::Completion, AgentError>
    where
        F: Fn() -> bool,
        E: FnMut(ProviderEvent) -> Result<(), BackendError>,
    {
        for iteration in 0..=max_iterations {
            if is_cancelled() {
                return Err(BackendError::Cancelled.into());
            }
            let definitions: Vec<crate::tools::ToolDefinition> = self
                .tools
                .as_ref()
                .map(|runtime| {
                    runtime
                        .registry
                        .definitions()
                        .into_iter()
                        .filter(|definition| self.skills.tool_allowed(&definition.name))
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default();
            let prepared = crate::context::prepare_context(
                self.session.turns(),
                self.context_budget,
                is_cancelled,
            )
            .map_err(|error| AgentError::InvalidTurn(error.to_string()))?;
            if let Some(governance) = self.governance.as_mut() {
                governance
                    .charge(
                        crate::governance::ResourceKind::InputTokens,
                        prepared.estimate.input_tokens,
                    )
                    .and_then(|_| {
                        governance.charge(crate::governance::ResourceKind::NetworkRequests, 1)
                    })
                    .map_err(|error| AgentError::Governance(error.to_string()))?;
                governance
                    .persist(&mut self.session)
                    .map_err(|error| AgentError::Governance(error.to_string()))?;
            }
            if let Some(checkpoint) = &prepared.checkpoint {
                let operation_id = format!("compaction-{}", checkpoint.source_sha256);
                self.session
                    .begin_operation(&crate::session::InterruptedOperation {
                        operation_id: operation_id.clone(),
                        kind: crate::session::OperationKind::Compaction,
                        turn_id: turn_id.to_owned(),
                        retry_requires_confirmation: false,
                    })?;
                self.session.append_event(serde_json::json!({
                    "type": "context_compacted",
                    "checkpoint": checkpoint,
                }))?;
                self.session
                    .finish_operation(&operation_id, crate::session::OperationOutcome::Succeeded)?;
            }
            let instructions = self.skills.effective_instructions();
            let request = CompletionRequest::new(
                turn_id,
                &prepared.turns,
                self.model.as_deref(),
                &definitions,
            )
            .with_instructions((!instructions.is_empty()).then_some(instructions.as_str()))
            .with_attachments(&self.active_attachments);
            let completion =
                self.backend
                    .complete_with_control(request, is_cancelled, &mut |event| {
                        provider_sink(event)?;
                        Ok(())
                    });
            let completion = completion.map_err(AgentError::from)?;
            if let Some(usage) = completion.usage
                && let Some(governance) = self.governance.as_mut()
            {
                governance
                    .charge(
                        crate::governance::ResourceKind::OutputTokens,
                        usage.output_tokens,
                    )
                    .and_then(|_| governance.persist(&mut self.session))
                    .map_err(|error| AgentError::Governance(error.to_string()))?;
            }
            if is_cancelled() {
                return Err(BackendError::Cancelled.into());
            }
            if completion.tool_calls.is_empty() {
                return Ok(completion);
            }
            if iteration == max_iterations {
                return Err(AgentError::ToolLoopLimit(max_iterations));
            }
            let Some(runtime) = self.tools.as_mut() else {
                return Err(AgentError::InvalidTurn(
                    "provider requested tools but no tool registry is configured".into(),
                ));
            };
            let calls = completion.tool_calls;
            // Preserve the provider's assistant function-call message in the
            // journal. Responses and Chat Completions both require that
            // message to precede their corresponding tool outputs when a
            // continuation request is issued.
            let call_metadata = calls
                .iter()
                .map(|call| {
                    serde_json::json!({
                        "id": call.id,
                        "name": call.name,
                        "arguments": call.arguments,
                    })
                })
                .collect::<Vec<_>>();
            let mut assistant_call = Turn::with_parent(
                next_id("assistant-tool-call"),
                turn_id.to_owned(),
                TurnRole::Assistant,
                String::new(),
            );
            assistant_call.metadata = Some(serde_json::json!({ "tool_calls": call_metadata }));
            self.session.append_turn(assistant_call)?;
            for call in calls {
                if is_cancelled() {
                    return Err(BackendError::Cancelled.into());
                }
                self.events.push(AgentEvent::ToolCall {
                    turn_id: turn_id.to_owned(),
                    call_id: call.id.clone(),
                    tool: call.name.clone(),
                });
                let tool_operation_id = format!("tool-{}", call.id);
                self.session
                    .begin_operation(&crate::session::InterruptedOperation {
                        operation_id: tool_operation_id.clone(),
                        kind: crate::session::OperationKind::Tool,
                        turn_id: turn_id.to_owned(),
                        retry_requires_confirmation: true,
                    })?;
                let definition = runtime.registry.definition(&call.name).cloned();
                if let Some(governance) = self.governance.as_mut()
                    && matches!(
                        definition.as_ref().map(|definition| definition.side_effect),
                        Some(crate::tools::ToolSideEffect::CommandExecution)
                    )
                {
                    governance
                        .charge(crate::governance::ResourceKind::Processes, 1)
                        .map_err(|error| AgentError::Governance(error.to_string()))?;
                }
                if !self.skills.tool_allowed(&call.name) {
                    let result = crate::tools::ToolResult::Error {
                        call_id: call.id.clone(),
                        tool: call.name.clone(),
                        error: crate::tools::ToolFailure {
                            code: crate::tools::ToolErrorCode::PolicyDenied,
                            message: "tool denied by skill policy".into(),
                        },
                    };
                    let serialized = serde_json::to_string(&result).map_err(|error| {
                        AgentError::InvalidTurn(format!(
                            "tool result serialization failed: {error}"
                        ))
                    })?;
                    let mut tool_turn = Turn::with_parent(
                        next_id("tool"),
                        turn_id.to_owned(),
                        TurnRole::Tool,
                        serialized,
                    );
                    tool_turn.metadata = Some(serde_json::json!({
                        "tool_call_id": call.id,
                        "tool_name": call.name,
                    }));
                    self.session.append_turn(tool_turn)?;
                    self.session.finish_operation(
                        &tool_operation_id,
                        crate::session::OperationOutcome::Failed,
                    )?;
                    self.events.push(AgentEvent::ToolResult {
                        turn_id: turn_id.to_owned(),
                        call_id: call.id,
                        success: false,
                    });
                    continue;
                }
                let approval = definition.as_ref().and_then(|definition| {
                    if runtime.policy.allows(definition.side_effect) {
                        runtime
                            .approval_policy
                            .decide(definition.side_effect, &call.name)
                    } else {
                        Some(ApprovalDecision::Deny)
                    }
                });
                if approval == Some(ApprovalDecision::Deny) {
                    let result = crate::tools::ToolResult::Error {
                        call_id: call.id.clone(),
                        tool: call.name.clone(),
                        error: crate::tools::ToolFailure {
                            code: crate::tools::ToolErrorCode::PolicyDenied,
                            message: "tool approval denied".into(),
                        },
                    };
                    let serialized = serde_json::to_string(&result).map_err(|error| {
                        AgentError::InvalidTurn(format!(
                            "tool result serialization failed: {error}"
                        ))
                    })?;
                    let mut tool_turn = Turn::with_parent(
                        next_id("tool"),
                        turn_id.to_owned(),
                        TurnRole::Tool,
                        serialized,
                    );
                    tool_turn.metadata = Some(serde_json::json!({
                        "tool_call_id": call.id,
                        "tool_name": call.name,
                    }));
                    self.session.append_turn(tool_turn)?;
                    self.events.push(AgentEvent::ToolResult {
                        turn_id: turn_id.to_owned(),
                        call_id: call.id,
                        success: false,
                    });
                    self.session.finish_operation(
                        &tool_operation_id,
                        crate::session::OperationOutcome::Failed,
                    )?;
                    continue;
                }
                if approval.is_none() {
                    let approval_request = ApprovalRequest {
                        request_id: format!("approval-{}", call.id),
                        turn_id: turn_id.to_owned(),
                        call_id: call.id.clone(),
                        tool: call.name.clone(),
                        side_effect: definition
                            .as_ref()
                            .map(|item| item.side_effect)
                            .unwrap_or(crate::tools::ToolSideEffect::ReadOnly),
                        arguments: call.arguments.clone(),
                    };
                    match runtime.approval.request(
                        approval_request,
                        &mut runtime.approval_policy,
                        is_cancelled,
                    ) {
                        Ok(ApprovalDecision::Allow) => {}
                        Ok(ApprovalDecision::Deny) | Err(_) => {
                            // A denied/cancelled approval is represented as a
                            // normal bounded tool result so the provider can
                            // explain it without executing the side effect.
                            let result = crate::tools::ToolResult::Error {
                                call_id: call.id.clone(),
                                tool: call.name.clone(),
                                error: crate::tools::ToolFailure {
                                    code: crate::tools::ToolErrorCode::PolicyDenied,
                                    message: "tool approval denied or cancelled".into(),
                                },
                            };
                            let serialized = serde_json::to_string(&result).map_err(|error| {
                                AgentError::InvalidTurn(format!(
                                    "tool result serialization failed: {error}"
                                ))
                            })?;
                            let mut tool_turn = Turn::with_parent(
                                next_id("tool"),
                                turn_id.to_owned(),
                                TurnRole::Tool,
                                serialized,
                            );
                            tool_turn.metadata = Some(serde_json::json!({
                                "tool_call_id": call.id,
                                "tool_name": call.name,
                            }));
                            self.session.append_turn(tool_turn)?;
                            self.events.push(AgentEvent::ToolResult {
                                turn_id: turn_id.to_owned(),
                                call_id: call.id,
                                success: false,
                            });
                            self.session.finish_operation(
                                &tool_operation_id,
                                crate::session::OperationOutcome::Failed,
                            )?;
                            continue;
                        }
                    }
                }
                let result = if call.name == "run_command"
                    && runtime
                        .policy
                        .allows(crate::tools::ToolSideEffect::CommandExecution)
                {
                    match call.arguments.as_object() {
                        Some(arguments) => match crate::tools::RunCommandTool::invoke_with_cancel(
                            &runtime.context,
                            arguments,
                            is_cancelled,
                        ) {
                            Ok(output) => crate::tools::ToolResult::Success {
                                call_id: call.id.clone(),
                                tool: call.name.clone(),
                                output,
                            },
                            Err(error) => crate::tools::ToolResult::Error {
                                call_id: call.id.clone(),
                                tool: call.name.clone(),
                                error: crate::tools::ToolFailure {
                                    code: error.code(),
                                    message: error.to_string(),
                                },
                            },
                        },
                        None => runtime.registry.execute_compact(
                            &runtime.context,
                            runtime.policy,
                            call.clone(),
                        ),
                    }
                } else {
                    runtime
                        .registry
                        .execute_compact(&runtime.context, runtime.policy, call.clone())
                };
                let result = crate::tools::compact_tool_result(&runtime.context, result)?;
                if matches!(
                    &result,
                    crate::tools::ToolResult::Error {
                        error: crate::tools::ToolFailure {
                            code: crate::tools::ToolErrorCode::Cancelled,
                            ..
                        },
                        ..
                    }
                ) {
                    self.session.finish_operation(
                        &tool_operation_id,
                        crate::session::OperationOutcome::Cancelled,
                    )?;
                    return Err(BackendError::Cancelled.into());
                }
                let success = result.is_success();
                let serialized = serde_json::to_string(&result).map_err(|error| {
                    AgentError::InvalidTurn(format!("tool result serialization failed: {error}"))
                })?;
                let mut tool_turn = Turn::with_parent(
                    next_id("tool"),
                    turn_id.to_owned(),
                    TurnRole::Tool,
                    serialized,
                );
                tool_turn.metadata = Some(serde_json::json!({
                    "tool_call_id": call.id,
                    "tool_name": call.name,
                }));
                self.session.append_turn(tool_turn)?;
                self.events.push(AgentEvent::ToolResult {
                    turn_id: turn_id.to_owned(),
                    call_id: call.id,
                    success,
                });
                self.session.finish_operation(
                    &tool_operation_id,
                    if success {
                        crate::session::OperationOutcome::Succeeded
                    } else {
                        crate::session::OperationOutcome::Failed
                    },
                )?;
            }
        }
        Err(AgentError::ToolLoopLimit(max_iterations))
    }

    /// Admit and, when accepted, immediately run one turn.
    pub fn process(&mut self, request: TurnInputRequest) -> Result<ProcessResult, AgentError> {
        self.process_with_cancel(request, || false)
    }

    /// Admit and run a turn with a cooperative cancellation predicate.
    pub fn process_with_cancel<F>(
        &mut self,
        request: TurnInputRequest,
        is_cancelled: F,
    ) -> Result<ProcessResult, AgentError>
    where
        F: Fn() -> bool,
    {
        self.process_with_cancel_and_events(request, is_cancelled, &mut |_| Ok(()))
    }

    pub fn process_with_cancel_and_events<F, E>(
        &mut self,
        request: TurnInputRequest,
        is_cancelled: F,
        provider_sink: &mut E,
    ) -> Result<ProcessResult, AgentError>
    where
        F: Fn() -> bool,
        E: FnMut(ProviderEvent) -> Result<(), BackendError>,
    {
        let submission = self.submit(request)?;
        if submission.accepted() {
            let assistant =
                self.run_active_turn_cancelable_with_events(is_cancelled, provider_sink)?;
            Ok(ProcessResult {
                submission,
                assistant,
            })
        } else {
            Ok(ProcessResult {
                submission,
                assistant: None,
            })
        }
    }

    /// Execute the portable live-steer fallback after the host has cancelled
    /// and joined the superseded provider request. The new durable user turn
    /// points at the old turn and is admitted exactly once.
    pub fn process_steer_reissue_with_events<F, E>(
        &mut self,
        message: String,
        superseded_turn_id: &str,
        is_cancelled: F,
        provider_sink: &mut E,
    ) -> Result<ProcessResult, AgentError>
    where
        F: Fn() -> bool,
        E: FnMut(ProviderEvent) -> Result<(), BackendError>,
    {
        let submission = self.start_reissued(message, superseded_turn_id)?;
        let assistant = self.run_active_turn_cancelable_with_events(is_cancelled, provider_sink)?;
        Ok(ProcessResult {
            submission,
            assistant,
        })
    }

    pub fn start_steer_reissue(
        &mut self,
        message: String,
        superseded_turn_id: &str,
    ) -> Result<TurnSubmission, AgentError> {
        self.start_reissued(message, superseded_turn_id)
    }

    pub fn append_handoff(&mut self, handoff: Handoff) -> Result<(), AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        let handoff_id = handoff.handoff_id.clone();
        let to = handoff.to.clone();
        self.session.append_handoff(handoff)?;
        self.events.push(AgentEvent::Handoff { handoff_id, to });
        Ok(())
    }

    /// Append a signed handoff after validating it against the session
    /// boundary. The record remains opaque to the turn state machine.
    pub fn append_handoff_record(&mut self, handoff: HandoffRecord) -> Result<(), AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        handoff.validate_for(&handoff.to, self.session.session_id())?;
        let handoff_id = handoff.claim_id.clone();
        let to = Some(handoff.to.clone());
        self.session.append_handoff_record(handoff)?;
        self.events.push(AgentEvent::Handoff { handoff_id, to });
        Ok(())
    }

    /// Replace the session only while idle.  The old store is moved out only
    /// after the new path has recovered successfully.
    pub fn resume_session(&mut self, path: impl Into<PathBuf>) -> Result<(), AgentError> {
        if self.phase == AgentPhase::Closed {
            return Err(AgentError::Closed);
        }
        if self.phase == AgentPhase::Running {
            return Err(AgentError::NotIdle);
        }
        let replacement = SessionStore::open(path.into())?;
        self.session = replacement;
        self.phase = AgentPhase::Idle;
        self.active_turn_id = None;
        self.active_attachments.clear();
        self.last_error = None;
        Ok(())
    }

    pub fn try_close(&mut self) -> Result<(), AgentError> {
        if self.phase == AgentPhase::Closed {
            return Ok(());
        }
        for (order, output) in self.skills.session_close_outputs().into_iter().enumerate() {
            self.session.append_event(serde_json::json!({
                "type": "skill_session_close",
                "order": order,
                "output": output,
            }))?;
        }
        self.phase = AgentPhase::Closed;
        self.active_turn_id = None;
        self.active_attachments.clear();
        Ok(())
    }

    pub fn close(&mut self) {
        if let Err(error) = self.try_close() {
            self.last_error = Some(error.to_string());
            self.events.push(AgentEvent::Error {
                message: error.to_string(),
            });
            self.phase = AgentPhase::Closed;
            self.active_turn_id = None;
            self.active_attachments.clear();
        }
    }
}

#[derive(Debug)]
pub struct ProcessResult {
    pub submission: TurnSubmission,
    pub assistant: Option<Turn>,
}

fn unix_time_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
        .min(u128::from(u64::MAX)) as u64
}

fn next_id(prefix: &str) -> String {
    format!(
        "{prefix}-{}-{}",
        unix_time_ms(),
        NEXT_ID.fetch_add(1, Ordering::Relaxed)
    )
}

fn attachment_journal_metadata(attachments: &[crate::backend::RequestAttachment]) -> Vec<Value> {
    attachments
        .iter()
        .map(|attachment| {
            serde_json::json!({
                "kind": attachment.input.kind,
                "mime_type": attachment.input.mime_type,
                "path": attachment.input.path,
                "url": attachment.input.url,
                "file_id": attachment.input.file_id,
                "size_bytes": attachment.size_bytes,
                "sha256": attachment.sha256,
            })
        })
        .collect()
}

/// Runtime mode.  There are intentionally only these two variants.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunMode {
    Tui,
    Headless,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CliOptions {
    pub mode: RunMode,
    pub session: PathBuf,
    pub backend: String,
    pub backend_explicit: bool,
    pub model: Option<String>,
    pub command: Option<CliCommand>,
    pub command_value: Option<String>,
    pub command_value2: Option<String>,
    pub retain_newest: Option<usize>,
    pub older_than_seconds: Option<u64>,
    pub json: bool,
    pub yes: bool,
    pub help: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CliCommand {
    ConfigImportCodex,
    ConfigDoctor,
    ConfigList,
    ConfigUse,
    PairImportCodex,
    PairStatus,
    PairRevoke,
    SessionList,
    SessionInspect,
    SessionFork,
    SessionExport,
    SessionImport,
    SessionGc,
    ExtensionList,
    ExtensionInstall,
    ExtensionRemove,
    ExtensionDisable,
    ExtensionEnable,
    ExtensionUpgrade,
}

impl Default for CliOptions {
    fn default() -> Self {
        Self {
            mode: RunMode::Tui,
            session: SessionStore::default_path(),
            backend: "openai".into(),
            backend_explicit: false,
            model: None,
            command: None,
            command_value: None,
            command_value2: None,
            retain_newest: None,
            older_than_seconds: None,
            json: false,
            yes: false,
            help: false,
        }
    }
}

pub fn parse_args<I, S>(args: I) -> Result<CliOptions, ZenpiError>
where
    I: IntoIterator<Item = S>,
    S: Into<String>,
{
    let mut options = CliOptions::default();
    let mut args = args.into_iter().map(Into::into).peekable();
    if args.peek().is_some_and(|argument| {
        matches!(
            argument.as_str(),
            "config" | "pair" | "session" | "extension"
        )
    }) {
        let group = args.next().unwrap_or_default();
        let action = args
            .next()
            .ok_or_else(|| ZenpiError::arguments(format!("{group} requires an action")))?;
        options.command = Some(match (group.as_str(), action.as_str()) {
            ("config", "import-codex") => CliCommand::ConfigImportCodex,
            ("config", "doctor") => CliCommand::ConfigDoctor,
            ("config", "list") => CliCommand::ConfigList,
            ("config", "use") => CliCommand::ConfigUse,
            ("pair", "import-codex") => CliCommand::PairImportCodex,
            ("pair", "status") => CliCommand::PairStatus,
            ("pair", "revoke") => CliCommand::PairRevoke,
            ("session", "list") => CliCommand::SessionList,
            ("session", "inspect") => CliCommand::SessionInspect,
            ("session", "fork") => CliCommand::SessionFork,
            ("session", "export") => CliCommand::SessionExport,
            ("session", "import") => CliCommand::SessionImport,
            ("session", "gc") => CliCommand::SessionGc,
            ("extension", "list") => CliCommand::ExtensionList,
            ("extension", "install") => CliCommand::ExtensionInstall,
            ("extension", "remove") => CliCommand::ExtensionRemove,
            ("extension", "disable") => CliCommand::ExtensionDisable,
            ("extension", "enable") => CliCommand::ExtensionEnable,
            ("extension", "upgrade") => CliCommand::ExtensionUpgrade,
            _ => {
                return Err(ZenpiError::arguments(format!(
                    "unknown {group} action `{action}`"
                )));
            }
        });
        while let Some(argument) = args.next() {
            match argument.as_str() {
                "--json"
                    if matches!(
                        options.command,
                        Some(
                            CliCommand::ConfigDoctor
                                | CliCommand::ConfigList
                                | CliCommand::PairStatus
                                | CliCommand::SessionList
                                | CliCommand::SessionInspect
                                | CliCommand::ExtensionList
                        )
                    ) =>
                {
                    options.json = true;
                }
                "--yes"
                    if matches!(
                        options.command,
                        Some(CliCommand::PairRevoke | CliCommand::SessionGc)
                    ) =>
                {
                    options.yes = true;
                }
                "--profile" => {
                    options.command_value = Some(
                        args.next()
                            .ok_or_else(|| ZenpiError::arguments("--profile requires a name"))?,
                    );
                }
                value
                    if matches!(options.command, Some(CliCommand::ConfigUse))
                        && options.command_value.is_none() =>
                {
                    options.command_value = Some(value.to_owned());
                }
                "--retain-newest" if matches!(options.command, Some(CliCommand::SessionGc)) => {
                    let value = args.next().ok_or_else(|| {
                        ZenpiError::arguments("--retain-newest requires a number")
                    })?;
                    options.retain_newest = Some(value.parse().map_err(|_| {
                        ZenpiError::arguments("--retain-newest must be a non-negative integer")
                    })?);
                }
                "--older-than-seconds"
                    if matches!(options.command, Some(CliCommand::SessionGc)) =>
                {
                    let value = args.next().ok_or_else(|| {
                        ZenpiError::arguments("--older-than-seconds requires a number")
                    })?;
                    options.older_than_seconds = Some(value.parse().map_err(|_| {
                        ZenpiError::arguments("--older-than-seconds must be a non-negative integer")
                    })?);
                }
                value
                    if matches!(
                        options.command,
                        Some(
                            CliCommand::SessionInspect
                                | CliCommand::SessionFork
                                | CliCommand::SessionExport
                                | CliCommand::SessionImport
                        )
                    ) && options.command_value.is_none() =>
                {
                    options.command_value = Some(value.to_owned());
                }
                value
                    if matches!(
                        options.command,
                        Some(
                            CliCommand::ExtensionInstall
                                | CliCommand::ExtensionRemove
                                | CliCommand::ExtensionDisable
                                | CliCommand::ExtensionEnable
                                | CliCommand::ExtensionUpgrade
                        )
                    ) && options.command_value.is_none() =>
                {
                    options.command_value = Some(value.to_owned());
                }
                value
                    if matches!(
                        options.command,
                        Some(
                            CliCommand::SessionFork
                                | CliCommand::SessionExport
                                | CliCommand::SessionImport
                        )
                    ) && options.command_value2.is_none() =>
                {
                    options.command_value2 = Some(value.to_owned());
                }
                _ => {
                    return Err(ZenpiError::arguments(format!(
                        "unsupported argument for {group} {action}: `{argument}`"
                    )));
                }
            }
        }
        if matches!(options.command, Some(CliCommand::ConfigUse)) && options.command_value.is_none()
        {
            return Err(ZenpiError::arguments("config use requires a profile name"));
        }
        if matches!(options.command, Some(CliCommand::PairRevoke)) && !options.yes {
            return Err(ZenpiError::arguments(
                "pair revoke requires --yes confirmation",
            ));
        }
        if matches!(options.command, Some(CliCommand::SessionInspect))
            && options.command_value.is_none()
        {
            return Err(ZenpiError::arguments("session inspect requires PATH"));
        }
        if matches!(
            options.command,
            Some(
                CliCommand::ExtensionInstall
                    | CliCommand::ExtensionRemove
                    | CliCommand::ExtensionDisable
                    | CliCommand::ExtensionEnable
                    | CliCommand::ExtensionUpgrade
            )
        ) && options.command_value.is_none()
        {
            return Err(ZenpiError::arguments(format!(
                "extension {action} requires a source path or extension name"
            )));
        }
        if matches!(
            options.command,
            Some(CliCommand::SessionFork | CliCommand::SessionExport | CliCommand::SessionImport)
        ) && (options.command_value.is_none() || options.command_value2.is_none())
        {
            return Err(ZenpiError::arguments(format!(
                "session {action} requires SOURCE and DESTINATION"
            )));
        }
        if matches!(options.command, Some(CliCommand::SessionGc))
            && (!options.yes
                || options.retain_newest.is_none()
                || options.older_than_seconds.is_none())
        {
            return Err(ZenpiError::arguments(
                "session gc requires --retain-newest N --older-than-seconds N --yes",
            ));
        }
        return Ok(options);
    }
    while let Some(argument) = args.next() {
        let (flag, inline) = argument
            .split_once('=')
            .map_or((argument.as_str(), None), |(flag, value)| {
                (flag, Some(value))
            });
        match flag {
            "--help" | "-h" => options.help = true,
            "--headless" => {
                if inline.is_some() {
                    return Err(ZenpiError::arguments("--headless does not take a value"));
                }
                options.mode = RunMode::Headless;
            }
            "--tui" => {
                if inline.is_some() {
                    return Err(ZenpiError::arguments("--tui does not take a value"));
                }
                options.mode = RunMode::Tui;
            }
            "--mode" => {
                let value = inline
                    .map(str::to_owned)
                    .or_else(|| args.next())
                    .ok_or_else(|| ZenpiError::arguments("--mode requires tui or headless"))?;
                options.mode = match value.as_str() {
                    "tui" => RunMode::Tui,
                    "headless" => RunMode::Headless,
                    _ => return Err(ZenpiError::arguments("--mode must be tui or headless")),
                };
            }
            "--session" => {
                let value = inline
                    .map(str::to_owned)
                    .or_else(|| args.next())
                    .ok_or_else(|| ZenpiError::arguments("--session requires a path"))?;
                if value.trim().is_empty() {
                    return Err(ZenpiError::arguments("--session path is empty"));
                }
                options.session = PathBuf::from(value);
            }
            "--backend" => {
                options.backend = inline
                    .map(str::to_owned)
                    .or_else(|| args.next())
                    .ok_or_else(|| ZenpiError::arguments("--backend requires echo or openai"))?;
                options.backend_explicit = true;
                if options.backend.trim().is_empty()
                    || options.backend.chars().any(char::is_control)
                {
                    return Err(ZenpiError::arguments("--backend name is invalid"));
                }
            }
            "--model" => {
                let model = inline
                    .map(str::to_owned)
                    .or_else(|| args.next())
                    .ok_or_else(|| ZenpiError::arguments("--model requires a name"))?;
                if model.trim().is_empty()
                    || model.len() > 256
                    || model.chars().any(char::is_control)
                {
                    return Err(ZenpiError::arguments(
                        "--model must be non-empty and at most 256 bytes",
                    ));
                }
                options.model = Some(model);
            }
            other if other.starts_with('-') => {
                return Err(ZenpiError::arguments(format!("unknown option `{other}`")));
            }
            other => {
                return Err(ZenpiError::arguments(format!(
                    "unexpected argument `{other}`"
                )));
            }
        }
    }
    Ok(options)
}

fn make_backend(options: &CliOptions) -> Result<Box<dyn Backend>, ZenpiError> {
    match options.backend.as_str() {
        "echo" if options.backend_explicit && cfg!(feature = "dev-fixtures") => {
            Ok(Box::new(EchoBackend))
        }
        "echo" => Err(ZenpiError::arguments(
            "echo is a test fixture; rebuild with --features dev-fixtures and pass --backend echo",
        )),
        "openai" => {
            let effective = crate::config::resolve_default(&crate::config::ConfigOverrides {
                backend: options.backend_explicit.then(|| options.backend.clone()),
                model: options.model.clone(),
                ..crate::config::ConfigOverrides::default()
            })?;
            let base_url = effective.base_url.ok_or_else(|| {
                ZenpiError::arguments(
                    "no provider URL configured; run `zenpi config import-codex` or set ZENPI_BASE_URL",
                )
            })?;
            let api_key = if effective.requires_openai_auth {
                Some(effective.api_key.ok_or_else(|| {
                    ZenpiError::arguments(
                        "no provider API key configured; run `zenpi config import-codex` or set ZENPI_API_KEY",
                    )
                })?)
            } else {
                effective.api_key
            };
            let model = effective.model.ok_or_else(|| {
                ZenpiError::arguments(
                    "no provider model configured; run `zenpi config import-codex` or set ZENPI_MODEL",
                )
            })?;
            let wire_api = effective
                .wire_api
                .as_deref()
                .unwrap_or("responses")
                .parse::<OpenAiWireApi>()?;
            let backend = OpenAiCompatibleBackend::from_values_with_settings_and_timeout(
                base_url,
                api_key,
                model,
                wire_api,
                effective.model_reasoning_effort,
                effective.model_verbosity,
                std::time::Duration::from_secs(effective.timeout_seconds.unwrap_or(120)),
            )?
            .with_max_retries(effective.max_retries.unwrap_or(2))?;
            Ok(Box::new(backend))
        }
        other => Err(ZenpiError::arguments(format!(
            "unknown backend `{other}` (expected echo or openai)"
        ))),
    }
}

fn print_help() {
    println!("zenpi [--mode tui|headless] [--session PATH] [--backend openai] [--model NAME]");
    println!("zenpi config import-codex [--profile NAME]");
    println!("zenpi config doctor [--profile NAME] [--json]");
    println!("zenpi config list [--json] | config use NAME");
    println!("zenpi pair import-codex|status|revoke --yes [--profile NAME]");
    println!("zenpi session list [--json] | inspect PATH [--json]");
    println!("zenpi session fork|export|import SOURCE DESTINATION");
    println!("zenpi session gc --retain-newest N --older-than-seconds N --yes");
    println!("zenpi extension list [--json] | install|upgrade PATH");
    println!("zenpi extension disable|enable|remove NAME");
    println!(
        "default provider: ~/.zenpi (or read-only ~/.codex fallback); echo exists only in dev-fixtures builds"
    );
}

/// Binary entry point shared with tests and embedders.
pub fn run() -> Result<(), ZenpiError> {
    let options = parse_args(env::args().skip(1))?;
    if options.help {
        print_help();
        return Ok(());
    }
    if let Some(command) = options.command {
        return match command {
            CliCommand::ConfigImportCodex | CliCommand::PairImportCodex => {
                let summary = match options.command_value.as_deref() {
                    Some(profile) => crate::config::import_codex_profile(profile)?,
                    None => crate::config::import_codex()?,
                };
                println!("{}", summary.display());
                Ok(())
            }
            CliCommand::ConfigDoctor | CliCommand::PairStatus => {
                let paths = crate::config::ConfigPaths::discover()?;
                let report =
                    crate::config::status_for_profile(&paths, options.command_value.as_deref())?;
                if options.json {
                    println!(
                        "{}",
                        serde_json::to_string(&report)
                            .map_err(|error| ZenpiError::Message(error.to_string()))?
                    );
                } else {
                    print_config_status(&report);
                }
                Ok(())
            }
            CliCommand::ConfigList => {
                let paths = crate::config::ConfigPaths::discover()?;
                let profiles = crate::config::list_profiles(&paths)?;
                if options.json {
                    println!(
                        "{}",
                        serde_json::to_string(&profiles)
                            .map_err(|error| ZenpiError::Message(error.to_string()))?
                    );
                } else if profiles.is_empty() {
                    println!(
                        "no named profiles (legacy default configuration may still be active)"
                    );
                } else {
                    for profile in profiles {
                        println!(
                            "{}{} provider={} model={} base_url={} wire_api={} api_key={}",
                            if profile.active { "* " } else { "  " },
                            profile.name,
                            display_option(profile.provider.as_deref()),
                            display_option(profile.model.as_deref()),
                            display_option(profile.base_url.as_deref()),
                            display_option(profile.wire_api.as_deref()),
                            if profile.api_key_present {
                                "present"
                            } else {
                                "missing"
                            },
                        );
                    }
                }
                Ok(())
            }
            CliCommand::ConfigUse => {
                let paths = crate::config::ConfigPaths::discover()?;
                let profile = options
                    .command_value
                    .as_deref()
                    .ok_or_else(|| ZenpiError::arguments("config use requires a profile name"))?;
                let changed = crate::config::use_profile(&paths, profile)?;
                println!("profile={profile} changed={changed}");
                Ok(())
            }
            CliCommand::PairRevoke => {
                let paths = crate::config::ConfigPaths::discover()?;
                let changed = crate::config::revoke(&paths, options.command_value.as_deref())?;
                println!("revoked={changed}");
                Ok(())
            }
            CliCommand::SessionList => {
                let paths = crate::config::ConfigPaths::discover()?;
                let sessions = crate::session::list_sessions(&paths.sessions)?;
                if options.json {
                    println!(
                        "{}",
                        serde_json::to_string(&sessions)
                            .map_err(|error| ZenpiError::Message(error.to_string()))?
                    );
                } else if sessions.is_empty() {
                    println!("no sessions");
                } else {
                    for session in sessions {
                        print_session_summary(&session);
                    }
                }
                Ok(())
            }
            CliCommand::SessionInspect => {
                let path = options
                    .command_value
                    .as_deref()
                    .ok_or_else(|| ZenpiError::arguments("session inspect requires PATH"))?;
                let session = crate::session::inspect_session(path)?;
                if options.json {
                    println!(
                        "{}",
                        serde_json::to_string(&session)
                            .map_err(|error| ZenpiError::Message(error.to_string()))?
                    );
                } else {
                    print_session_summary(&session.summary);
                    for turn in &session.turns {
                        println!("{:?}\t{}\t{}", turn.role, turn.id, turn.content);
                    }
                }
                Ok(())
            }
            CliCommand::SessionFork => {
                let (source, destination) = command_source_destination(&options)?;
                let source = SessionStore::open(source)?;
                let fork = source.fork_to(destination)?;
                print_session_summary(&fork.summary());
                Ok(())
            }
            CliCommand::SessionExport => {
                let (source, destination) = command_source_destination(&options)?;
                SessionStore::open(source)?.export_to(destination)?;
                println!("exported={destination}");
                Ok(())
            }
            CliCommand::SessionImport => {
                let (source, destination) = command_source_destination(&options)?;
                let imported = crate::session::import_session(source, destination)?;
                print_session_summary(&imported.summary());
                Ok(())
            }
            CliCommand::SessionGc => {
                let paths = crate::config::ConfigPaths::discover()?;
                let removed = crate::session::garbage_collect_sessions(
                    &paths.sessions,
                    crate::session::GarbageCollectionPolicy {
                        retain_newest: options.retain_newest.unwrap_or_default(),
                        older_than_ms: options
                            .older_than_seconds
                            .unwrap_or_default()
                            .saturating_mul(1_000),
                    },
                    crate::session::unix_time_ms(),
                )?;
                for path in &removed {
                    println!("removed={}", path.display());
                }
                println!("removed_count={}", removed.len());
                Ok(())
            }
            CliCommand::ExtensionList => {
                let paths = crate::config::ConfigPaths::discover()?;
                let catalog = crate::extensions::ExtensionCatalog::load(&paths.extensions)
                    .map_err(|error| ZenpiError::Message(error.to_string()))?;
                if options.json {
                    println!(
                        "{}",
                        serde_json::to_string(catalog.summaries())
                            .map_err(|error| ZenpiError::Message(error.to_string()))?
                    );
                } else if catalog.summaries().is_empty() {
                    println!("no extensions");
                } else {
                    for extension in catalog.summaries() {
                        println!(
                            "{} {} disabled={} compatible={} tools={}",
                            extension.name,
                            extension.version,
                            extension.disabled,
                            extension.compatible,
                            extension.tools.join(","),
                        );
                    }
                }
                Ok(())
            }
            CliCommand::ExtensionInstall | CliCommand::ExtensionUpgrade => {
                let paths = crate::config::ConfigPaths::discover()?;
                let source =
                    PathBuf::from(options.command_value.as_deref().ok_or_else(|| {
                        ZenpiError::arguments("extension source path is required")
                    })?);
                let summary = if command == CliCommand::ExtensionInstall {
                    crate::extensions::install(&paths.extensions, &source)
                } else {
                    crate::extensions::upgrade(&paths.extensions, &source)
                }
                .map_err(|error| ZenpiError::Message(error.to_string()))?;
                println!("extension={} version={}", summary.name, summary.version);
                Ok(())
            }
            CliCommand::ExtensionRemove => {
                let paths = crate::config::ConfigPaths::discover()?;
                let name = options
                    .command_value
                    .as_deref()
                    .ok_or_else(|| ZenpiError::arguments("extension name is required"))?;
                let changed = crate::extensions::remove(&paths.extensions, name)
                    .map_err(|error| ZenpiError::Message(error.to_string()))?;
                println!("removed={changed}");
                Ok(())
            }
            CliCommand::ExtensionDisable | CliCommand::ExtensionEnable => {
                let paths = crate::config::ConfigPaths::discover()?;
                let name = options
                    .command_value
                    .as_deref()
                    .ok_or_else(|| ZenpiError::arguments("extension name is required"))?;
                let disabled = command == CliCommand::ExtensionDisable;
                let changed = crate::extensions::set_disabled(&paths.extensions, name, disabled)
                    .map_err(|error| ZenpiError::Message(error.to_string()))?;
                println!("disabled={disabled} changed={changed}");
                Ok(())
            }
        };
    }
    let backend = make_backend(&options)?;
    let session = SessionStore::open(&options.session)?;
    let mut agent = Agent::new(session, backend);
    let _ = agent.acknowledge_recovery()?;
    // Advertise the complete bounded tool set. Side effects still cannot run
    // until the local approval policy grants the individual call.
    let workspace = env::current_dir()?;
    let mut tools = crate::tools::ToolRegistry::with_all_builtins()
        .map_err(|error| ZenpiError::Message(format!("tool registry: {error}")))?;
    let paths = crate::config::ConfigPaths::discover()?;
    let extensions = crate::extensions::ExtensionCatalog::load(&paths.extensions)
        .map_err(|error| ZenpiError::Message(format!("extension loading: {error}")))?;
    extensions
        .register_tools(&mut tools)
        .map_err(|error| ZenpiError::Message(format!("extension tools: {error}")))?;
    let tool_context = crate::tools::ToolContext::new(workspace)
        .map_err(|error| ZenpiError::Message(format!("tool workspace: {error}")))?;
    agent.set_tools(
        tools,
        tool_context,
        crate::tools::SideEffectPolicy::all_builtins(),
    );
    let approval_mode = match options.mode {
        RunMode::Headless => crate::approval::ApprovalMode::Always,
        RunMode::Tui => crate::approval::ApprovalMode::ReadOnly,
    };
    let _ = agent.set_approval_policy(crate::approval::ApprovalPolicy {
        mode: approval_mode,
        ..crate::approval::ApprovalPolicy::default()
    });
    let project_skills = env::current_dir()?.join(".zenpi").join("skills");
    let skills = crate::skills::SkillSet::load(&paths.skills, &project_skills)
        .map_err(|error| ZenpiError::Message(format!("skill loading: {error}")))?;
    agent.set_skills(skills);
    if let Some(model) = options.model {
        agent.set_model(Some(model))?;
    }
    match options.mode {
        RunMode::Headless => crate::headless::run_stdio_owned(agent)
            .map_err(|error| ZenpiError::Message(error.to_string())),
        RunMode::Tui => crate::tui::run_async(agent),
    }
}

fn display_option(value: Option<&str>) -> &str {
    value.unwrap_or("<not configured>")
}

fn command_source_destination(options: &CliOptions) -> Result<(&str, &str), ZenpiError> {
    let source = options
        .command_value
        .as_deref()
        .ok_or_else(|| ZenpiError::arguments("session command requires SOURCE"))?;
    let destination = options
        .command_value2
        .as_deref()
        .ok_or_else(|| ZenpiError::arguments("session command requires DESTINATION"))?;
    Ok((source, destination))
}

fn print_session_summary(summary: &crate::session::SessionSummary) {
    println!(
        "session={} path={} turns={} events={} handoffs={} warnings={} next_seq={}",
        summary.session_id,
        summary.path,
        summary.turn_count,
        summary.event_count,
        summary.handoff_count,
        summary.recovery_warnings,
        summary.next_seq,
    );
}

fn print_config_status(report: &crate::config::ConfigStatus) {
    println!("profile={}", display_option(report.profile.as_deref()));
    println!(
        "ready={}",
        (!report.requires_openai_auth || report.api_key_present)
            && report.base_url.is_some()
            && report.model.is_some()
    );
    println!("backend={}", report.backend);
    println!("provider={}", display_option(report.provider.as_deref()));
    println!("base_url={}", display_option(report.base_url.as_deref()));
    println!("wire_api={}", display_option(report.wire_api.as_deref()));
    println!("model={}", display_option(report.model.as_deref()));
    println!("requires_openai_auth={}", report.requires_openai_auth);
    println!("supports_websockets={}", report.supports_websockets);
    println!(
        "api_key={}",
        if report.api_key_present {
            "present"
        } else {
            "missing"
        }
    );
}
