//! Shared zenpi library. The binary exposes only TUI and headless modes.

pub mod approval;
pub mod b3;
pub mod backend;
pub mod config;
pub mod context;
pub mod core;
pub mod diagnostics;
pub mod domain_store;
pub mod domains;
pub mod error;
pub mod extensions;
pub mod governance;
pub mod headless;
pub mod layout;
pub mod protocol;
pub mod render;
pub mod resources;
pub mod runtime;
pub mod runtime_intent;
pub mod security;
pub mod session;
pub mod skills;
pub mod slash;
pub mod slash_actions;
pub mod tools;
pub mod tui;
pub mod view_model;
